### PR TITLE
Document how to fix macOS/Python 3.6 certificate issue

### PR DESCRIPTION
**Pull request by machristie**
This pull request documents how I fixed an SSL issue that seems like it will likely hit everyone running Python 3.6+ on macOS.

### CODE REVIEW

**Comment by machristie** [comment]
Sounds good @nuwang, will do

**Comment by machristie** [comment]
@nuwang I've moved the documentation to a separate page. Please review when you have a chance.

**Comment by afgane** [comment]
Thanks for the update. I'll merge this but then rename the page from _Common setup issues_ to _Troubleshooting_ because we don't commonly see issues ;)

**Comment by machristie** [comment]
Makes sense 😄 Thanks!

**Pull request merged**
